# Generated by Django 5.0 on 2023-12-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprompt',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
