# Generated by Django 5.0 on 2023-12-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_app', '0002_individualprompt_title'),
        ('writing_collections', '0002_remove_writingcollection_privacy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprompt',
            name='writing_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing_collections.writingcollection'),
        ),
    ]
